---
development:
  DB_FILENAME: infrastructure/database/dev.db
  FACEBOOK_URL: https://www.facebook.com/
  DEFAULT_RECIPE_IMAGE_URL: https://clubreduva.com/wp-content/uploads/2015/12/default-recipe.png
test:
  DB_FILENAME: infrastructure/database/test.db
  FACEBOOK_URL: https://www.facebook.com/
  DEFAULT_RECIPE_IMAGE_URL: https://clubreduva.com/wp-content/uploads/2015/12/default-recipe.png
production:
  FACEBOOK_URL: https://www.facebook.com/
  DEFAULT_RECIPE_IMAGE_URL: https://clubreduva.com/wp-content/uploads/2015/12/default-recipe.png
