---
development:
  DB_FILENAME: infrastructure/database/dev.db
  FACEBOOK_URL: https://www.facebook.com/
test:
  DB_FILENAME: infrastructure/database/test.db
  FACEBOOK_URL: https://www.facebook.com/
production:
  FACEBOOK_URL: https://www.facebook.com/
